export const UPDATING_THUMBNAIL = 'UPDATING_THUMBNAIL';
export const UPDATING_THUMBNAIL_FAILED = 'UPDATING_THUMBNAIL_FAILED';
export const UPDATING_THUMBNAIL_SUCCESS = 'UPDATING_THUMBNAIL_SUCCESS';
export const FETCHING_VIDEOS = 'FETCHING_VIDEOS';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILED = 'FETCHING_FAILED';
export const UPDATE_CURRENT_VIDEO = 'UPDATE_CURRENT_VIDEO';
